version: '3.4'
services:
  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent
    restart: unless-stopped
    ports:
      - 8200:8200
    volumes:
      - ${ROOT}\qbittorrent\config:/config
      - ${ROOT}\predownloads:/downloads
      - ${ROOT}\downloads\torrent-blackhole:/downloads/torrent-blackhole
    environment:
      - TZ=${TZ} # timezone, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - PUID=${PUID} # default user id, defined in .env
      - WEBUI_PORT=8200
  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    ports:
      - 9117:9117
    volumes:
      - ${ROOT}\downloads\torrent-blackhole:/downloads/torrent-blackhole # place where to put .torrent files for manual download
      - ${ROOT}\config\jackett:/config # config files
  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    ports:
      - 6789:6789
    volumes:
      - ${ROOT}\predownloads:/downloads # download folder
      - ${ROOT}\config\nzbget:/config # config files
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    ports:
      - 8989:8989
    volumes:
      - ${ROOT}\config\sonarr:/config # config files
      - ${ROOT}\media\tv:/tv # tv shows folder
      - ${ROOT}\downloads:/downloads # download folder
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    ports:
      - 7878:7878
    volumes:
      - ${ROOT}\config\radarr:/config # config files
      - ${ROOT}\media\movies:/movies # movies folder
      - ${ROOT}\downloads:/downloads # download folder
  handbrake:
    container_name: handbrake
    image: jlesage/handbrake
    restart: unless-stopped
    environment:
      - AUTOMATED_CONVERSION_PRESET=myh265
      - AUTOMATED_CONVERSION_FORMAT=mkv
      - AUTOMATED_CONVERSION_KEEP_SOURCE=0
      - AUTOMATED_CONVERSION_OUTPUT_SUBDIR=SAME_AS_SRC
      - AUTOMATED_CONVERSION_CHECK_INTERVAL=60
      - HANDBRAKE_DEBUG=1
    ports:
      - 5803:5800
    volumes:
      - ${ROOT}\predownloads:/watch:rw # watch folder
      - ${ROOT}\downloads:/output:rw # output folder
      - ${ROOT}\handbrake:/config:rw
      - ${ROOT}\handbrake:/storage:ro
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin
    restart: unless-stopped
    ports:
      - 8096:8096
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    environment:
      - TZ=${TZ} # timezone, defined in .env
      - PUID=${PUID}
      - PGID=${PGID}
      - JELLYFIN_PublishedServerUrl=http://local.jellyfin.com
    volumes:
      - ${ROOT}\jellyfin\config:/config
      - ${ROOT}\media\tv:/data/tvshows
      - ${ROOT}\media\movies:/data/movies
  # glances:
  #   image: docker.io/nicolargo/glances
  #   container_name: glances
  #   restart: always
  #   network_mode: host
  #   pid: host
  #   ports:
  #     - 61208:61208
  #   volumes:
  #       - /media:/media
  #       - /var/run/docker.sock:/var/run/docker.sock:ro
  #   environment:
  #     - GLANCES_OPT=-w
  #     - PGID=1000
  #     - PUID=1000
